server.port=${PORT:8080}
spring.application.name=busbackend
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.datasource.username=4CsmVsPGB2nxMH9.root
spring.datasource.password=Mx24MJP1a9cDfgDh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
