server.port=${PORT:8080}
spring.application.name=busbackend
spring.datasource.url=jdbc:mysql://localhost:3306/bus_tracker
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
